import sys
import re
import random
from datetime import date
from dateutil.relativedelta import relativedelta

import random
import time
import names

import ships
import people

YEAR_OFFSET = 200

def generate(obj,min,max):
    # Creates an array of objects of given class
    objects = []
    amount = random.randint(min,max)
    for x in range(0, amount):
        objects.append(obj())
    return objects

def romanNumeral(integer):
    returnstring=''
    table=[['M',1000],['CM',900],['D',500],['CD',400],['C',100],['XC',90],['L',50],['XL',40],['X',10],['IX',9],['V',5],['IV',4],['I',1]]
    for pair in table:
        while integer-pair[1]>=0:
            integer-=pair[1]
            returnstring+=pair[0]
    return returnstring

def pickDate():
    start_date = date.today().replace(day=1, month=1).toordinal()
    end_date = date.today().toordinal()
    random_day = date.fromordinal(random.randint(start_date, end_date))
    random_day = random_day + relativedelta(years=YEAR_OFFSET+random.randint(0,100))
    return random_day

def subtractYears(base,amount):
    date = base - relativedelta(years=amount)
    return date

def addYears(base,amount):
    date = base + relativedelta(years=amount)
    return date

def roll(dice):
  result = False
  while (result == False):
    for i in range(0, len(dice)):
      value = random.random()
      if random.random() < dice[i]['chance']:
        result = dice[i]
  return result 

def pick(name):
    module = sys.modules[__name__]
    seperator = '.'

    if(seperator in name):
        # Nested
        parts = name.split(seperator)
        if len(parts) == 2:
            template = random.choice(getattr(module, parts[0])[parts[1]])
        if len(parts) == 3:
            template = random.choice(getattr(module, parts[0])[parts[1]][parts[2]])
        if len(parts) == 4:
            template = random.choice(getattr(module, parts[0])[parts[1]][parts[2]][parts[3]])
    else:
        # Flat
        template = random.choice(getattr(module, name))
    return parse(template)
    
def parse(template):
    module = sys.modules[__name__]
    seperator = '.'

    # Parse template
    if (type(template) == str):        
        tags = re.findall('<.*?>', template)
        rgx = re.compile('[%s]' % '<>')
                
        for tag in tags:
            value = rgx.sub('', tag)

            if(seperator in value):
                # Nested
                parts = value.split(seperator)
                                            
                if len(parts) == 2:
                    value = random.choice(getattr(module, parts[0])[parts[1]])
                if len(parts) == 3:
                    value = random.choice(getattr(module, parts[0])[parts[1]][parts[2]])
                if len(parts) == 4:
                    value = random.choice(getattr(module, parts[0])[parts[1]][parts[2]][parts[3]])    
            else:
                # Flat
                value = random.choice(getattr(module, value))
    
            # Replace the tag with the value
            template = template.replace(tag,value);

    return template


places = {
    "birthplaces" : [
        "<places.qualifier.singular> somewhere in the <astronomy.constellation> system",
        "<places.qualifier.plural> a <places.town> town on <astronomy.planet.name> <astronomy.numeral>",
        "<places.qualifier.plural> the borderlands of the <astronomy.planet.name> outpost on <astronomy.constellation> <astronomy.numeral>",
        "<places.qualifier.singular> a frontier colony on <astronomy.constellation> <astronomy.numeral>",
        "<places.qualifier.singular> a well established colony on <astronomy.planet.name>",
        "<places.qualifier.plural> the <places.type> city of <astronomy.planet.name> on <astronomy.constellation> <astronomy.numeral>",
        "<places.qualifier.plural> the <places.type> city of <astronomy.planet.name>",
        "<places.qualifier.plural> the <places.type> moon of <astronomy.planet.name> in <astronomy.constellation>",
        "<places.qualifier.singular> <astronomy.planet.name> Outpost",
        "<places.qualifier.plural> <astronomy.planet.name> Spaceport",
        "<places.qualifier.singular> <astronomy.planet.name> Starport",
        "<places.qualifier.singular> a listening station on <astronomy.planet.name>",
        "<places.qualifier.singular> a communications relay station on <astronomy.planet.name> <astronomy.numeral>",
        "<places.qualifier.singular> a satellite relay station orbiting <astronomy.planet.name> <astronomy.numeral>",
        "<places.qualifier.singular> an orbital relay station near <astronomy.planet.name> <astronomy.numeral>",
        "<places.qualifier.plural> an outpost on <astronomy.planet.name> <astronomy.numeral>",
        "<places.qualifier.plural> <astronomy.planet.name> City on <astronomy.constellation>",
        "<places.qualifier.plural> <astronomy.planet.name> Colony on <astronomy.constellation>",
        "<places.qualifier.plural> a military base on <astronomy.planet.name> <astronomy.numeral>",
        "<places.qualifier.plural> a shipyard town on <astronomy.planet.name> <astronomy.numeral>",
        "<places.qualifier.plural> the gas mines of <astronomy.planet.name> <astronomy.numeral>",
        "<places.qualifier.plural> The <astronomy.planet.name> Terraform Complex",
        "<places.qualifier.plural> The <astronomy.planet.name> Mining Complex",
        "<places.qualifier.plural> The <astronomy.planet.name> Refinery Complex",
        "<places.qualifier.plural> The <astronomy.planet.name> Industrial Complex",
        "<places.qualifier.plural> the <places.type> city of <astronomy.planet.name> <astronomy.numeral>",
        "<places.qualifier.plural> the largest moon of <astronomy.constellation>",
        "<places.qualifier.plural> the second moon of <astronomy.constellation>",
        "<places.qualifier.plural> a colony on the first moon of <astronomy.planet.name> in the <astronomy.constellation> system",
    ],
    "qualifier" : {
        "singular" : [
            "is originally from",
            "is from",
            "was born on",
            "was raised on ",
        ],
        "plural" : [
            "is originally from",
            "is from",
            "was born in",
            "was raised in",
        ],
    },
    "town" : [
        "",
        "small",
        "fairly small",
        "rural",
        "farming",
        "quiet",
    ],
    "type" : [
        "industrial",
        "military",
        "peaceful",
        "isolated",
        "remote",
        "desert",
        "forest",
        "frozen",
        "cloud",
        "old",
        "ancient",
        "capital",
        "lawless",
    ],
}

astronomy = {
    "planet" : {
        "name" : [
            "Abatos",
            "Abyssus",
            "Achylia",
            "Ackenia",
            "Ackisia",
            "Aeneas",
            "Aesculus",
            "Ageenia",
            "Ageicia",
            "Agricola",
            "Agripeta",
            "Aleania",
            "Alvus",
            "Amethystus",
            "Ampelos",
            "Anchises",
            "Andabata",
            "Angilia",
            "Anusia",
            "Aparctias",
            "Aposplenos",
            "Archimandrita",
            "Arelia",
            "Athesia",
            "Athleta",
            "Athylia",
            "Atomus",
            "Auriga",
            "Awycia",
            "Banilia",
            "Baptista",
            "Belinia",
            "Bubsequa",
            "Caelicola",
            "Canonista",
            "Catoblepas",
            "Cedrus",
            "Celtae",
            "Ceracia",
            "Cerasus",
            "Chaocia",
            "Chausia",
            "Cherronesus",
            "Chersonesus",
            "Clepta",
            "Conlega",
            "Cornus",
            "Cupressus",
            "Danenia",
            "Danista",
            "Delos",
            "Drapeta",
            "Druidae",
            "Drysidae",
            "Echenia",
            "Elminia",
            "Eminia",
            "Emisia",
            "Enalia",
            "Enasia",
            "Enenia",
            "Engasia",
            "Engenia",
            "Enginia",
            "Engolia",
            "Erycia",
            "Erynia",
            "Essonia",
            "Estilia",
            "Estonia",
            "Fagus",
            "Fraxinus",
            "Gagates",
            "Galaxias",
            "Garesia",
            "Garycia",
            "Garynia",
            "Gaster",
            "Hatalia",
            "Hatosia",
            "Hinesia",
            "Hinucia",
            "Hippotoxotae",
            "Honycia",
            "Humus",
            "Iania",
            "Idiota",
            "Idololatres",
            "Ightylia",
            "Ildecia",
            "Ildolia",
            "Imocia",
            "Inaelia",
            "Incola",
            "Itasia",
            "Itonia",
            "Kalalia",
            "Kelesia",
            "Kelinia",
            "Kinocia",
            "Lanista",
            "Laurus",
            "Lesbos",
            "Lyeasia",
            "Lyeosia",
            "Malus",
            "Mandragoras",
            "Matricida",
            "Methodos",
            "Mithras",
            "Moabites",
            "Monticola",
            "Morilia",
            "Morus",
            "Mosisia",
            "Myrtus",
            "Nalania",
            "Nauta",
            "Navita",
            "Neanias",
            "Nyalia",
            "Nyania",
            "Nyesia",
            "Oldulia",
            "Oldycia",
            "Onania",
            "Orisia",
            "Ornus",
            "Orocia",
            "Orolia",
            "Orylia",
            "Osynia",
            "Oughesia",
            "Palaestes",
            "Palmatias",
            "Pampinus",
            "Pandectes",
            "Peltastes",
            "Peracia",
            "Persicus",
            "Pinus",
            "Pirata",
            "Platanus",
            "Poeta",
            "Pololia",
            "Polulia",
            "Populus",
            "Propheta",
            "Prunus",
            "Quaecia",
            "Quaisia",
            "Qualia",
            "Queesia",
            "Radisia",
            "Radysia",
            "Rakelia",
            "Rakolia",
            "Ranenia",
            "Raycia",
            "Rayocia",
            "Rilicia",
            "Rodylia",
            "Ruricola",
            "Rynolia",
            "Sacricola",
            "Sambucus",
            "Samesia",
            "Samisia",
            "Satrapa",
            "Sayalia",
            "Scriba",
            "Seralia",
            "Serilia",
            "Shyalia",
            "Shyocia",
            "Shyunia",
            "Sophistes",
            "Sorites",
            "Sulocia",
            "Sycophanta",
            "Taiosia",
            "Taisia",
            "Tasicia",
            "Tasynia",
            "Tata",
            "Taxus",
            "Telirrhizos",
            "Therulia",
            "Tiaylia",
            "Tonocia",
            "Toralia",
            "Transfuga",
            "Turania",
            "Turynia",
            "Tyrannicida",
            "Tyrus",
            "Untalia",
            "Unticia",
            "Untisia",
            "Untysia",
            "Urnilia",
            "Uskilia",
            "Ustysia",
            "Vannus",
            "Vappa",
            "Verynia",
            "Waresia",
            "Xiphias",
            "Zelotes",
            "Serouos",
            "Risoeos",
            "Vehios",
            "Polatia",
            "Shyayos",
            "Shyeos",
            "Nizeios",
            "Rhaisios",
            "Ineayos",
            "Nyaos",
            "Niateios",
            "Yidios",
            "Cevios",
            "Chrazaos",
            "Rolios",
            "Ustayos",
            "Thrisaos",
            "Baneos",
            "Mofios",
            "Kekeios",
            "Asheos",
            "Luilios",
            "Bureos",
            "Cholaios",
            "Iritia",
            "Torutia",
            "Daulios",
            "Ardaeos",
            "Nalios",
            "Smuryos",
            "Tonetia",
            "Eraos",
            "Ustutia",
            "Dymios",
            "Crevaios",
            "Chudeios",
            "Danuos",
            "Ghaotia",
            "Echeatia",
            "Chaitia",
            "Nubios",
            "Angautia",
            "Kimeitia",
            "Joldios",
            "Dracios",
            "Lanios",
            "Toraitia",
            "Rievios",
            "Blunios",
            "Ceuraos",
            "Leykyios",
            "Drayrios",
            "Whiakios",
            "Tinaeos",
            "Iroios",
            "Ightitia",
            "Whiwios",
            "Featuios",
            "Stoogios",
            "Yeriatia",
            "Yorios",
            "Endyos",
            "Swuiloios",
            "Iautia",
            "Polotia",
            "Undeos",
            "Hoetios",
            "Iauos",
            "Siduos",
            "Carios",
            "Hecoios",
            "Needios",
            "Garaos",
            "Delyos",
            "Smuitios",
            "Ireitia",
            "Aldeos",
            "Deleos",
            "Mosuos",
            "Haucios",
            "Sayloios",
            "Strifuos",
            "Stoukios",
            "Leretia",
            "Hinoutia",
            "Ardeos",
            "Ranatia",
            "Likyos",
            "Engoos",
            "Aldaos",
            "Ardoos",
            "Bitios",
            "Ranaios",
            "Isoios",
            "Aleutia",
            "Stefeos",
            "Loreos",
            "Sonoios",
            "Danoitia",
            "Snodios",
            "Croutoos",
            "Clekios",
            "Snasheios",
            "Pauboios",
            "Tuwios",
            "Voreos",
            "Rynaos",
            "Livios",
            "Danoitia",
            "Ageootia",
            "Issauos",
            "Onotia",
            "Nyhios",
            "Woroos",
            "Higeos",
            "Ardaos",
            "Cheitia",
            "Etitia",
            "Engeytia"
        ],
    },
    "constellation" : [
        "Andromeda",
        "Antlia",
        "Apus",
        "Aquarius",
        "Aquila",
        "Ara",
        "Aries",
        "Auriga",
        "Bootes",
        "Caelum",
        "Camelopardalis",
        "Cancer",
        "Canes",
        "Venatici",
        "Canis",
        "Major",
        "Canis",
        "Minor",
        "Capricornus",
        "Carina",
        "Cassiopeia",
        "Centaurus",
        "Cepheus",
        "Cetus",
        "Chamaeleon",
        "Circinus",
        "Columba",
        "Coma",
        "Berenices",
        "Corona",
        "Australis",
        "Corona",
        "Borealis",
        "Corvus",
        "Crater",
        "Crux",
        "Cygnus",
        "Delphinus",
        "Dorado",
        "Draco",
        "Equuleus",
        "Eridanus",
        "Fornax",
        "Gemini",
        "Grus",
        "Hercules",
        "Horologium",
        "Hydra",
        "Hydrus",
        "Indus",
        "Lacerta",
        "Leo",
        "Leo",
        "Minor",
        "Lepus",
        "Libra",
        "Lupus",
        "Lynx",
        "Lyra",
        "Mensa",
        "Microscopium",
        "Monoceros",
        "Musca",
        "Norma",
        "Octans",
        "Ophiuchus",
        "Orion",
        "Pavo",
        "Pegasus",
        "Perseus",
        "Phoenix",
        "Pictor",
        "Pisces",
        "Piscis",
        "Austrinus",
        "Puppis",
        "Pyxis",
        "Reticulum",
        "Sagitta",
        "Sagittarius",
        "Scorpius",
        "Sculptor",
        "Scutum",
        "Serpens",
        "Sextans",
        "Taurus",
        "Telescopium",
        "Triangulum",
        "Triangulum",
        "Australe",
        "Tucana",
        "Ursa",
        "Major",
        "Ursa",
        "Minor",
        "Vela",
        "Virgo",
        "Volans",
        "Vulpecula"
    ],
    "numeral" : [
        "",
        "Prime",
        "I",
        "II",
        "III",
        "IV",
        "V",
        "VI",
        "VII",
        "VIII",
        "IX",
    ]
}

appearance = {
    "hair" : {
        "color" :   [
            "auburn",
            "black",
            "jet black",
            "blonde",
            "brown",
            "dark brown",
            "dull blonde",
            "golden-blonde",
            "light brown",
            "platinum blonde",
            "red",
            "strawberry blonde"
        ],
        "length" :  [
            "long",
            "mid-length",
            "short",
        ],
        "type" :    [
            "straight",
            "fine",
            "thick",
            "wavy",
            "curly"            
        ],
        "style" : {
            "male" :    [
                "left uncut",
                "cut short",
                "in a butch cut",
                "in a crew cut",
                "in a flattop",
                "cut regular",
                "in a military standard cut",
                "in a military regular cut"
            ],
            "female" :  [
                "neatly braided",
                "cut short",
                "in a <appearance.hair.length> braid",
                "in a <appearance.hair.length> ponytail",
                "left uncut",
                "pinned neatly back",
                "worn <appearance.hair.length>",
                "worn loose about the shoulders"
            ]
        }
    },
    "eyes" : {
        "color" : [
            "blue",
            "brown",
            "dark brown",
            "gray",
            "green",
            "hazel"
        ]
    },
    "skin" : {
        "color" : [
            "pasty",
            "flawless",
            "radiant",
            "dark",
            "deep dark",
            "fair",
            "freckled",
            "pale",
            "olive",
            "dark olive",
            "tanned",
            "rosy"        
        ]
    },
    "build" : {
        "male" : [
            "fit",
            "chubby",
            "attractive",
            "very good looking",
            "quite attractive",
            "somewhat unattractive",
            "portly",
            "angular",
            "skinny",
            "well-built",
            "slender",
            "lean",
            "heavyset",
            "athletic",
            "quite athletic",
            "quite thin",
            "somewhat thin",
            "of average weight",
            "a bit pudgy",
            "quite heavy",
            "fairly muscular",
            "quite muscular"
        ],
        "female" : [
            "fit",
            "thick",
            "attractive",
            "very good looking",
            "quite attractive",
            "somewhat unattractive",
            "plump",
            "shapely",
            "skinny",
            "well-built",
            "slender",
            "lean",
            "heavyset",
            "curvaceous",
            "athletic",
            "quite athletic",
            "quite thin",
            "somewhat thin",
            "of average weight",
            "a bit pudgy",
            "quite heavy",
            "fairly muscular",
            "quite muscular"
        ]
    },
    "height" : [
        "of average height",
        "tall",
        "a little tall",
        "very tall",
        "a little less than average height",
        "short",
        "a little short",
        "very short"
    ]
}

personality = {
    "trait" : {
        "positive" : [
            "accessible",
            "active",
            "adaptable",
            "admirable",
            "adventurous",
            "agreeable",
            "alert",
            "allocentric",
            "amiable",
            "anticipative",
            "appreciative",
            "articulate",
            "aspiring",
            "athletic",
            "attractive",
            "balanced",
            "benevolent",
            "brilliant",
            "calm",
            "capable",
            "captivating",
            "caring",
            "challenging",
            "charismatic",
            "charming",
            "cheerful",
            "clean",
            "clear-headed",
            "clever",
            "colorful",
            "companionly",
            "compassionate",
            "conciliatory",
            "confident",
            "conscientious",
            "considerate",
            "constant",
            "contemplative",
            "cooperative",
            "courageous",
            "courteous",
            "creative",
            "cultured",
            "curious",
            "daring",
            "debonair",
            "decent",
            "decisive",
            "dedicated",
            "deep",
            "dignified",
            "directed",
            "disciplined",
            "discreet",
            "dramatic",
            "dutiful",
            "dynamic",
            "earnest",
            "ebullient",
            "educated",
            "efficient",
            "elegant",
            "eloquent",
            "empathetic",
            "energetic",
            "enthusiastic",
            "esthetic",
            "exciting",
            "extraordinary",
            "fair",
            "faithful",
            "farsighted",
            "felicific",
            "firm",
            "flexible",
            "focused",
            "forecful",
            "forgiving",
            "forthright",
            "freethinking",
            "friendly",
            "fun-loving",
            "gallant",
            "generous",
            "gentle",
            "genuine",
            "good-natured",
            "gracious",
            "hardworking",
            "healthy",
            "hearty",
            "helpful",
            "herioc",
            "high-minded",
            "honest",
            "honorable",
            "humble",
            "humorous",
            "idealistic",
            "imaginative",
            "impressive",
            "incisive",
            "incorruptible",
            "independent",
            "individualistic",
            "innovative",
            "inoffensive",
            "insightful",
            "insouciant",
            "intelligent",
            "intuitive",
            "invulnerable",
            "kind",
            "knowledgeble",
            "leaderly",
            "leisurely",
            "liberal",
            "logical",
            "lovable",
            "loyal",
            "lyrical",
            "magnanimous",
            "many-sided",
            "masculine",
            "mature",
            "methodical",
            "maticulous",
            "moderate",
            "modest",
            "multi-leveled",
            "neat",
            "nonauthoritarian",
            "objective",
            "observant",
            "open",
            "optimistic",
            "orderly",
            "organized",
            "original",
            "painstaking",
            "passionate",
            "patient",
            "patriotic",
            "peaceful",
            "perceptive",
            "perfectionist",
            "personable",
            "persuasive",
            "planful",
            "playful",
            "polished",
            "popular",
            "practical",
            "precise",
            "principled",
            "profound",
            "protean",
            "protective",
            "providential",
            "prudent",
            "punctual",
            "pruposeful",
            "rational",
            "realistic",
            "reflective",
            "relaxed",
            "reliable",
            "resourceful",
            "respectful",
            "responsible",
            "responsive",
            "reverential",
            "romantic",
            "rustic",
            "sage",
            "sane",
            "scholarly",
            "scrupulous",
            "secure",
            "selfless",
            "self-critical",
            "self-defacing",
            "self-denying",
            "self-reliant",
            "self-sufficent",
            "sensitive",
            "sentimental",
            "seraphic",
            "serious",
            "shrewd",
            "simple",
            "skillful",
            "sober",
            "sociable",
            "solid",
            "sophisticated",
            "spontaneous",
            "sporting",
            "stable",
            "steadfast",
            "steady",
            "stoic",
            "strong",
            "studious",
            "suave",
            "subtle",
            "sweet",
            "sympathetic",
            "systematic",
            "tasteful",
            "thorough",
            "tidy",
            "tolerant",
            "tractable",
            "trusting",
            "uncomplaining",
            "understanding",
            "undogmatic",
            "unfoolable",
            "upright",
            "urbane",
            "venturesome",
            "vivacious",
            "warm",
            "well-bred",
            "well-read",
            "well-rounded",
            "winning",
            "wise",
            "witty",
            "youthful",
            "absentminded",
            "aggressive",
            "ambitious",
            "amusing",
        ],
        "neutral" : [
            "artful",
            "ascetic",
            "authoritarian",
            "big-thinking",
            "boyish",
            "breezy",
            "businesslike",
            "busy",
            "casual",
            "crebral",
            "chummy",
            "circumspect",
            "competitive",
            "complex",
            "confidential",
            "conservative",
            "contradictory",
            "crisp",
            "cute",
            "deceptive",
            "determined",
            "dominating",
            "dreamy",
            "driving",
            "droll",
            "dry",
            "earthy",
            "effeminate",
            "emotional",
            "enigmatic",
            "experimental",
            "familial",
            "folksy",
            "formal",
            "freewheeling",
            "frugal",
            "glamorous",
            "guileless",
            "high-spirited",
            "huried",
            "hypnotic",
            "iconoclastic",
            "idiosyncratic",
            "impassive",
            "impersonal",
            "impressionable",
            "intense",
            "invisible",
            "irreligious",
            "irreverent",
            "maternal",
            "mellow",
            "modern",
            "moralistic",
            "mystical",
            "neutral",
            "noncommittal",
            "noncompetitive",
            "obedient",
            "old-fashined",
            "ordinary",
            "outspoken",
            "paternalistic",
            "physical",
            "placid",
            "political",
            "predictable",
            "preoccupied",
            "private",
            "progressive",
            "proud",
            "pure",
            "questioning",
            "quiet",
            "religious",
            "reserved",
            "restrained",
            "retiring",
            "sarcastic",
            "self-conscious",
            "sensual",
            "skeptical",
            "smooth",
            "soft",
            "solemn",
            "solitary",
            "stern",
            "stoiid",
            "strict",
            "stubborn",
            "stylish",
            "subjective",
            "surprising",
            "soft",
            "tough",
            "unaggressive",
            "unambitious",
            "unceremonious",
            "unchanging",
            "undemanding",
            "unfathomable",
            "unhurried",
            "uninhibited",
            "unpatriotic",
            "unpredicatable",
            "unreligious",
            "unsentimental",
            "whimsical"
        ],
        "negitive" : [
            "abrasive",
            "abrupt",
            "agonizing",
            "aimless",
            "airy",
            "aloof",
            "amoral",
            "angry",
            "anxious",
            "apathetic",
            "arbitrary",
            "argumentative",
            "arrogantt",
            "artificial",
            "asocial",
            "assertive",
            "astigmatic",
            "barbaric",
            "bewildered",
            "bizarre",
            "bland",
            "blunt",
            "biosterous",
            "brittle",
            "brutal",
            "calculating",
            "callous",
            "cantakerous",
            "careless",
            "cautious",
            "charmless",
            "childish",
            "clumsy",
            "coarse",
            "cold",
            "colorless",
            "complacent",
            "complaintive",
            "compulsive",
            "conceited",
            "condemnatory",
            "conformist",
            "confused",
            "contemptible",
            "conventional",
            "crafty",
            "crass",
            "crazy",
            "criminal",
            "critical",
            "crude",
            "cruel",
            "cynical",
            "decadent",
            "deceitful",
            "delicate",
            "demanding",
            "dependent",
            "desperate",
            "destructive",
            "devious",
            "difficult",
            "dirty",
            "disconcerting",
            "discontented",
            "discouraging",
            "discourteous",
            "dishonest",
            "disloyal",
            "disobedient",
            "disorganized",
            "disputatious",
            "disrespectful",
            "disruptive",
            "dissolute",
            "dissonant",
            "distractible",
            "disturbing",
            "dogmatic",
            "domineering",
            "dull",
            "easily discouraged",
            "egocentric",
            "enervated",
            "envious",
            "erratic",
            "escapist",
            "excitable",
            "expedient",
            "extravagant",
            "extreme",
            "faithless",
            "false",
            "fanatical",
            "fanciful",
            "fatalistic",
            "fawning",
            "fearful",
            "fickle",
            "fiery",
            "fixed",
            "flamboyant",
            "foolish",
            "forgetful",
            "fraudulent",
            "frightening",
            "frivolous",
            "gloomy",
            "graceless",
            "grand",
            "greedy",
            "grim",
            "gullible",
            "hateful",
            "haughty",
            "hedonistic",
            "hesitant",
            "hidebound",
            "high-handed",
            "hostile",
            "ignorant",
            "imitative",
            "impatient",
            "impractical",
            "imprudent",
            "impulsive",
            "inconsiderate",
            "incurious",
            "indecisive",
            "indulgent",
            "inert",
            "inhibited",
            "insecure",
            "insensitive",
            "insincere",
            "insulting",
            "intolerant",
            "irascible",
            "irrational",
            "irresponsible",
            "irritable",
            "lazy",
            "libidinous",
            "loquacious",
            "malicious",
            "mannered",
            "mannerless",
            "mawkish",
            "mealymouthed",
            "mechanical",
            "meddlesome",
            "melancholic",
            "meretricious",
            "messy",
            "miserable",
            "miserly",
            "misguided",
            "mistaken",
            "money-minded",
            "monstrous",
            "moody",
            "morbid",
            "muddle-headed",
            "naive",
            "narcissistic",
            "narrow",
            "narrow-minded",
            "negativistic",
            "neglectful",
            "neurotic",
            "nihilistic",
            "obnoxious",
            "obsessive",
            "obvious",
            "odd",
            "offhand",
            "one-dimensional",
            "one-sided",
            "opinionated",
            "opportunistic",
            "oppressed",
            "outrageous",
            "overimaginative",
            "paranoid",
            "passive",
            "pedantic",
            "perverse",
            "petty",
            "pharissical",
            "phlegmatic",
            "plodding",
            "pompous",
            "possessive",
            "power-hungry",
            "predatory",
            "prejudiced",
            "presumptuous",
            "pretentious",
            "prim",
            "procrastinating",
            "profligate",
            "provocative",
            "pugnacious",
            "puritanical",
            "quirky",
            "reactionary",
            "reactive",
            "regimental",
            "regretful",
            "repentant",
            "repressed",
            "resentful",
            "ridiculous",
            "rigid",
            "ritualistic",
            "rowdy",
            "ruined",
            "sadistic",
            "sanctimonious",
            "scheming",
            "scornful",
            "secretive",
            "sedentary",
            "selfish",
            "self-indulgent",
            "shallow",
            "shortsighted",
            "shy",
            "silly",
            "single-minded",
            "sloppy",
            "slow",
            "sly",
            "small-thinking",
            "softheaded",
            "sordid",
            "steely",
            "stiff",
            "strong-willed",
            "stupid",
            "submissive",
            "superficial",
            "superstitious",
            "suspicious",
            "tactless",
            "tasteless",
            "tense",
            "thievish",
            "thoughtless",
            "timid",
            "transparent",
            "treacherous",
            "trendy",
            "troublesome",
            "unappreciative",
            "uncaring",
            "uncharitable",
            "unconvincing",
            "uncooperative",
            "uncreative",
            "uncritical",
            "unctuous",
            "undisciplined",
            "unfriendly",
            "ungrateful",
            "unhealthy",
            "unimaginative",
            "unimpressive",
            "unlovable",
            "unpolished",
            "unprincipled",
            "unrealistic",
            "unreflective",
            "unreliable",
            "unrestrained",
            "unself-critical",
            "unstable",
            "vacuous",
            "vague",
            "venal",
            "venomous",
            "vindictive",
            "vulnerable",
            "weak",
            "weak-willed",
            "well-meaning",
            "willful",
            "wishful",
            "zany"
        ]
    }
}

words = {
    "intensity" : [
        "slighly",
        "somewhat",
        "quite",
        "rather",
        "very",
        "strikingly",
        "extremely",
    ]
}

ranks = {
  "enlisted" : [
    {"designation":"E-1","abbrivation":"CA","title":"Crewman Apprentice",           "chance":.043},
    {"designation":"E-2","abbrivation":"CN","title":"Crewman",                      "chance":.053},
    {"designation":"E-3","abbrivation":"SP","title":"Specialist",                   "chance":.180},
    {"designation":"E-4","abbrivation":"PO3","title":"Petty Officer 3rd Class",     "chance":.190},
    {"designation":"E-4","abbrivation":"PO2","title":"Petty Officer 2nd Class",     "chance":.230},
    {"designation":"E-5","abbrivation":"PO1","title":"Petty Officer 1st Class",     "chance":.170},
    {"designation":"E-6","abbrivation":"CPO","title":"Chief Petty Officer",         "chance":.076},
    {"designation":"E-7","abbrivation":"SCPO","title":"Senior Chief Petty Officer", "chance":.021},
    {"designation":"E-8","abbrivation":"MCPO","title":"Master Chief Petty Officer", "chance":.008},
  ] ,
  "officer" : [
    {"designation":"O-1","abbrivation":"ENS","title":"Ensign",                      "chance":.040},
    {"designation":"O-2","abbrivation":"LTJG","title":"Lieutenant Junior Grade",    "chance":.050},
    {"designation":"O-3","abbrivation":"LT","title":"Lieutenant",                   "chance":.300},
    {"designation":"O-4","abbrivation":"LCDR","title":"Lieutenant Commander",       "chance":.100},
    {"designation":"O-5","abbrivation":"CDR","title":"Commander",                   "chance":.050},
    {"designation":"O-6","abbrivation":"CAPT","title":"Captain",                    "chance":.030},
    {"designation":"O-7","abbrivation":"RDML","title":"Rear Admiral (lower half)",  "chance":.003},
    {"designation":"O-8","abbrivation":"RADM","title":"Rear Admiral (upper half)",  "chance":.001},
    {"designation":"O-9","abbrivation":"VADM","title":"Vice Admiral",               "chance":.001},
  ],
  "marine" : [
    {"designation":"E-1","abbrivation":"PVT","title":"Private",            "chance":.043},
    {"designation":"E-2","abbrivation":"PFC","title":"Private First Class","chance":.053},
    {"designation":"E-3","abbrivation":"LCPL","title":"Lance Corporal",    "chance":.120},
    {"designation":"E-4","abbrivation":"CPL","title":"Corporal",           "chance":.080},
    {"designation":"E-5","abbrivation":"SGT","title":"Sergeant",           "chance":.030},
    {"designation":"E-6","abbrivation":"SSGT","title":"Staff Sergeant",    "chance":.020},
    {"designation":"E-7","abbrivation":"GYSSGT","title":"Gunnery Sergeant",    "chance":.010},
    {"designation":"E-8","abbrivation":"MSGT","title":"Master Sergeant",    "chance":.005},
    {"designation":"E-8","abbrivation":"1STSGT","title":"First Sergeant",    "chance":.005},
  ],
  "commander" : [
    {"designation":"O-4","abbrivation":"LCDR","title":"Lieutenant Commander",       "chance":.100},
    {"designation":"O-5","abbrivation":"CDR","title":"Commander",                   "chance":.050},
  ],
  "high ranking officer" : [
    {"designation":"O-6","abbrivation":"CAPT","title": "Captain",                    "chance":.040},
    {"designation":"O-7","abbrivation":"RDML","title": "Admiral",                    "chance":.010},
    {"designation":"O-9","abbrivation":"VADM","title": "Vice Admiral",               "chance":.001},
  ]
}

ship = {
    "type" : [
        {"name" : "Star Carrier",
        "designation" : "CV/CVN",
        "divisions" : ["AD","AMA","A","C","CS","D","E","L","M","MAR","MED","NAV","OPS","PA","NUKE","SAF","SUP","TR","W"]
        },
        {"name" : "Light Star Carrier",
        "designation" : "CVL",
        "divisions" : ["AD","AMA","A","C","CS","D","E","M","MED","NAV","OPS","PA","NUKE","SAF","SUP","TR","W"]
        },
        {"name" : "Escort Star Carrier",
        "designation" : "CVE",
        "divisions" : ["AD","AMA","A","CS","D","E","M","MED","NAV","OPS","PA","NUKE","SAF","SUP","TR","W"]
        },
        {"name" : "Battleship",
        "designation" : "BB",
        "divisions" : ["AD","ART","CS","D","E","M","MED","NAV","OPS","NUKE","SAF","SUP","W"]
        },
        {"name" : "Heavy Gunship",
        "designation" : "GSA",
        "divisions" : ["CS","ART","E","M","NAV","OPS","NUKE","SAF","W"]
        },
        {"name" : "Guided Missile Cruiser",
        "designation" : "CAG/CGN",
        "divisions" : ["AD","CS","D","E","M","MED","NAV","OPS","NUKE","SAF","SUP","TR","W"]
        },
        {"name" : "Heavy Cruiser",
        "designation" : "CA",
        "divisions" : ["AD","CS","D","E","M","MED","NAV","OPS","NUKE","SAF","SUP","TR","W"]
        },
        {"name" : "Light Cruiser",
        "designation" : "CL",
        "divisions" : ["AD","CS","D","E","M","MED","NAV","OPS","NUKE","SAF","SUP","TR","W"]
        },
        {"name" : "Destroyer",
        "designation" : "DD",
        "divisions" : ["AD","CS","D","E","M","MED","NAV","OPS","NUKE","SAF","SUP","TR","W"]
        },
        {"name" : "Guided Missile Destroyer",
        "designation" : "DDG",
        "divisions" : ["AD","CS","D","E","M","MED","NAV","OPS","NUKE","SAF","SUP","TR","W"]
        },
        {"name" : "Destroyer Escort",
        "designation" : "DE",
        "divisions" : ["AD","CS","D","E","M","MED","NAV","OPS","NUKE","SAF","SUP","TR","W"]
        },
        {"name" : "Frigate",
        "designation" : "FF",
        "divisions" : ["AD","CS","D","E","M","MAR","MED","NAV","OPS","NUKE","SAF","SUP","TR","W"]
        },
        {"name" : "Guided Missile Frigate",
        "designation" : "FFG",
        "divisions" : ["AD","CS","D","E","M","MED","NAV","OPS","NUKE","SAF","SUP","TR","W"]
        },
        {"name" : "Ground Combat Ship",
        "designation" : "LCS",
        "divisions" : ["CS","E","M","MED","NAV","OPS","W"]
        },
        {"name" : "Ground Assault Ship",
        "designation" : "LCA",
        "divisions" : ["CS","E","M","MED","NAV","OPS","W","MEU"]
        },
        {"name" : "Guided Missile Prowler",
        "designation" : "SSG/AGSS",
        "divisions" : ["CS","E","M","MED","NAV","OPS","W"]
        },
        {"name" : "Attack Prowler",
        "designation" : "SSN",
        "divisions" : ["CS","E","M","MED","NAV","OPS","W"]
        },
        {"name" : "Ballistic Prowler",
        "designation" : "SSBN",
        "divisions" : ["CS","E","M","MED","NAV","OPS","W"]
        },
        {"name" : "Guided Missile Prowler",
        "designation" : "SSGN",
        "divisions" : ["CS","E","M","MED","NAV","OPS","W"]
        },
        {"name" : "Orbital Assault Ship",
        "designation" : "LHA/LHD",
        "divisions" : ["CS","E","M","NAV","OPS","W"]
        },
        {"name" : "Orbital Command Ship",
        "designation" : "LCC",
        "divisions" : ["AD","AMA","C","CS","COM","D","E","L","M","MED","NAV","OPS","PA","NUKE","SAF","SUP","TR","W"]
        },
        {"name" : "Orbital Transport Dock",
        "designation" : "LPD",
        "divisions" : ["CS","E","M","MED","NAV","OPS","W"]
        },
        {"name" : "Attack / Orbital Cargo Ship",
        "designation" : "AKA/LKA",
        "divisions" : ["CS","E","M","MED","NAV","OPS","W"]
        },
        {"name" : "Dock Landing Ship",
        "designation" : "LSD",
        "divisions" : ["CS","E","MED","NAV","OPS","W"]
        },
        {"name" : "Landing Ship",
        "designation" : "LST",
        "divisions" : ["LS","NAV"]
        },
        {"name" : "Dropship",
        "designation" : "LCM/LCU",
        "divisions" : ["AC","MAR"]
        },
        {"name" : "Mechanized and Utility Dropship",
        "designation" : "LCM/LCU",
        "divisions" : ["AC","GUN","M","MAR"]
        },
        {"name" : "Heavy Assault Dropship",
        "designation" : "LHAC",
        "divisions" : ["AC","GUN","MAR"]
        },
        {"name" : "Oribtal Patrol",
        "designation" : "PC",
        "divisions" : ["CS","NAV","OPS"]
        },
        {"name" : "Patrol Combatant Missile (Suborbital)",
        "designation" : "PHM",
        "divisions" : ["CS","NAV","SAF"]
        },
        {"name" : "Asterioid Minesweeper",
        "designation" : "MSO",
        "divisions" : ["NAV","OPS"]
        },
        {"name" : "Orbital Minehunter",
        "designation" : "MHC",
        "divisions" : ["CS","NAV","OPS"]
        },
        {"name" : "Mine Countermeasures Ship",
        "designation" : "MCM",
        "divisions" : ["CS","NAV","OPS"]
        },
        {"name" : "Mine Countermeasures Support Ship",
        "designation" : "MCS",
        "divisions" : ["CS","NAV","OPS"]
        },
        {"name" : "Ammunition Ship",
        "designation" : "AE",
        "divisions" : ["E","M","NAV","OPS","SUP"]
        },
        {"name" : "Stellar Maintenance Logistics Ship",
        "designation" : "AVB",
        "divisions" : ["E","M","MED","NAV","OPS","SUP"]
        },
        {"name" : "Solar Repair Ship",
        "designation" : "ARC",
        "divisions" : ["D","E","M","NAV","OPS","SUP"]
        },
        {"name" : "Cargo Ship",
        "designation" : "AK",
        "divisions" : ["E","NAV","OPS","SUP"]
        },
        {"name" : "Combat Stores Ship",
        "designation" : "AD",
        "divisions" : ["NAV","OPS","SUP"]
        },
        {"name" : "Command Ship",
        "designation" : "AGF",
        "divisions" : ["AD","AMA","C","CS","D","E","L","M","MAR","MED","NAV","OPS","PA","NUKE","SAF","SUP","TR","W"]
        },
        {"name" : "Communications Relay Ship",
        "designation" : "ACS",
        "divisions" : ["COM","E","NAV","OPS"]
        },
        {"name" : "Destroyer Tender",
        "designation" : "AD",
        "divisions" : ["E","NAV","OPS"]
        },
        {"name" : "Dry Cargo / Ammunition Ship",
        "designation" : "AKE",
        "divisions" : ["NAV","OPS","SUP"]
        },
        {"name" : "Fast Combat Support Ship",
        "designation" : "AOE",
        "divisions" : ["E","M","NAV","OPS","SUP"]
        },
        {"name" : "Stellar Research Ship",
        "designation" : "AGOR",
        "divisions" : ["COM","E","NAV","OPS","MED","SCI"]
        },
        {"name" : "Combat Logistics Ship",
        "designation" : "AO",
        "divisions" : ["E","NAV","OPS","SUP"]
        },
        {"name" : "Fuel Tanker",
        "designation" : "AOG",
        "divisions" : ["SUP","OPS","NAV"]
        },
        {"name" : "Hospital Ship",
        "designation" : "AH",
        "divisions" : ["HOS","NAV","OPS","L"]
        },
        {"name" : "Stellar Surveillance Ship",
        "designation" : "AGOS",
        "divisions" : ["COM","E","NAV","OPS","MED","SCI"]
        },
        {"name" : "Repair Ship",
        "designation" : "AR",
        "divisions" : ["D","E","M","NAV","OPS","MED"]
        },
        {"name" : "Replenishment Oiler",
        "designation" : "AOR",
        "divisions" : ["E","NAV","OPS"]
        },
        {"name" : "Rescue and Salvage Ship",
        "designation" : "ARS",
        "divisions" : ["E","NAV","OPS","SUP"]
        },
        {"name" : "Starport Tender",
        "designation" : "AV",
        "divisions" : ["E","NAV","OPS","SUP"]
        },
        {"name" : "Stores Ship",
        "designation" : "AF",
        "divisions" : ["E","NAV","OPS","SUP"]
        },
        {"name" : "Prowler Rescue Ship",
        "designation" : "ASR",
        "divisions" : ["M","E","NAV","OPS","SUP"]
        },
        {"name" : "Survey Ship",
        "designation" : "AGS",
        "divisions" : ["COM","E","NAV","MED","SRV"]
        },
        {"name" : "Vehicle Cargo Ship",
        "designation" : "AKR",
        "divisions" : ["D","NAV","SUP","OPS"]
        },
        {"name" : "Mobile Landing Platform Ship",
        "designation" : "MLP",
        "divisions" : ["D","E","NAV","SUP","LS"]
        }
    ],
    "division" : {
        "AD" :  { "name" : "Administrative", "size" : 2,           "rank":.2 },
        "AMA" : { "name" : "Spacecraft Maintenance", "size" : 7,   "rank":.1 },
        "ART" : { "name" : "Artillery Crew", "size" : 5,           "rank":.2 },
        "C" :   { "name" : "Chaplain", "size" : 1,               "rank":.8 },
        "CS" :  { "name" : "Combat Systems", "size" : 10,          "rank":.1 },
        "COM" : { "name" : "Communications", "size" : 5,           "rank":.2 },
        "D" :   { "name" : "Deck Department", "size" : 10,         "rank":.0 },
        "E" :   { "name" : "Engineering", "size" : 5,              "rank":.1 },
        "GUN" : { "name" : "Gun Crew", "size" : 1,                 "rank":.2 },
        "L" :   { "name" : "Legal", "size" : 1,                   "rank":.9 },
        "LS" :  { "name" : "Landing Systems", "size" : 3,          "rank":.2 },
        "M" :   { "name" : "Maintenance", "size" : 5,              "rank":.2 },
        "MED" : { "name" : "Medical", "size" : 2,                  "rank":.3 },
        "HOS" : { "name" : "Hospital Staff", "size" : 10,          "rank":.8 },
        "NAV" : { "name" : "Navigation", "size" : 3,               "rank":.2 },
        "NUKE" :{ "name" : "Reactor / FTL", "size" : 6,            "rank":.4 },
        "OPS" : { "name" : "Operations", "size" : 7,               "rank":.3 },
        "PA" :  { "name" : "Public Affairs", "size" : 1,         "rank":.9 },
        "SAF" : { "name" : "Safety", "size" : 3,                   "rank":.2 },
        "SUP" : { "name" : "Supply", "size" : 9,                   "rank":.2 },
        "SRV" : { "name" : "Survey Analysis", "size" : 4,          "rank":.0 },
        "TR" :  { "name" : "Training", "size" : 5,                 "rank":.2 },
        "W" :   { "name" : "Weapons", "size" : 5,                  "rank":.1 },
        "MAR" : { "name" : "Marine Detachment",         "size" : 4, "marines" : True, "rank":.1 },
        "MEU" : { "name" : "Marine Expeditionary Unit", "size" : 24,"marines" : True, "rank":.2 },
        "A" :   { "name" : "Air Wing", "size" : 5, "callsigns" : True,   "rank":1 },
        "AC" :  { "name" : "Air Crew", "size" : 2, "callsigns" : True,   "rank":.3 },
        "SCI" : { "name" : "Astronomy and Astrophysics Department", "size" : 5,   "rank":.6 },
    }
}

# Character development data for writers and authors
character = {
    "motivations": {
        "primary": [
            "seeking revenge for a past betrayal",
            "trying to protect their family from danger",
            "desperately searching for acceptance and belonging",
            "driven to prove their worth to those who doubted them",
            "haunted by guilt and seeking redemption",
            "fighting against an unjust system",
            "pursuing a lost love across time and space",
            "trying to escape their predetermined destiny",
            "seeking knowledge that could change everything",
            "protecting an innocent from corruption",
            "trying to restore their tarnished reputation",
            "pursuing power to prevent future suffering",
            "seeking to understand their true identity",
            "driven by an unshakeable sense of justice",
            "trying to break free from family expectations",
            "seeking to master a dangerous ability",
            "driven to uncover a family secret",
            "trying to save their dying world/community",
            "pursuing immortality to protect others",
            "seeking to right an ancient wrong"
        ],
        "antagonist": [
            "convinced their harsh methods serve the greater good",
            "seeking to impose order on a chaotic world",
            "driven by a twisted sense of justice",
            "believing others are too weak to handle the truth",
            "seeking revenge for a perceived betrayal",
            "trying to prevent a future they've foreseen",
            "convinced that emotion makes people weak",
            "seeking to purify the world of corruption",
            "driven by jealousy of others' happiness",
            "believing they alone can save everyone",
            "seeking to prove their superiority",
            "trying to control others to protect them",
            "convinced that suffering builds character",
            "seeking to eliminate what they see as weakness"
        ]
    },
    "flaws": {
        "major": [
            "chronically dishonest, even to themselves",
            "unable to trust anyone completely",
            "prone to violent outbursts when threatened",
            "paralyzed by indecision at crucial moments",
            "addicted to danger and risky behavior",
            "manipulative and controlling in relationships",
            "consumed by jealousy and envy",
            "pathologically afraid of abandonment",
            "obsessed with perfection to a destructive degree",
            "unable to forgive past hurts",
            "compulsively seeks others' approval",
            "ruthlessly ambitious, regardless of cost",
            "emotionally distant and unavailable",
            "prone to self-destructive behavior",
            "unable to accept help from others"
        ],
        "minor": [
            "terrible with money and finances",
            "chronically late to important events",
            "overly critical of others' mistakes",
            "talks too much when nervous",
            "holds grudges over small slights",
            "terrible at reading social cues",
            "overly competitive about trivial things",
            "procrastinates on important decisions",
            "jumps to conclusions without evidence",
            "interrupts others constantly",
            "makes jokes at inappropriate times",
            "overly dramatic about minor problems",
            "forgets important dates and names",
            "judges others too quickly",
            "terrible at keeping secrets"
        ],
        "heroic": [
            "too willing to sacrifice themselves for others",
            "refuses to compromise their principles",
            "takes responsibility for everything that goes wrong",
            "unable to see the darkness in people they care about",
            "pushes others away to protect them",
            "won't ask for help even when desperate",
            "forgives too easily and gets hurt repeatedly",
            "sees the good in everyone, even enemies"
        ]
    },
    "fears": [
        "being abandoned by everyone they love",
        "losing control of their own mind",
        "being revealed as a fraud or impostor",
        "causing harm to innocent people",
        "being trapped in a confined space",
        "losing their memories and identity",
        "being judged for their past mistakes",
        "failing to protect those they care about",
        "being alone for the rest of their life",
        "losing their independence or freedom",
        "being possessed or controlled by another",
        "watching their loved ones suffer",
        "being unable to change or grow",
        "becoming the monster they fight against",
        "being forgotten after they die",
        "losing their ability to feel emotions",
        "being betrayed by someone they trust",
        "reliving their worst trauma repeatedly",
        "being powerless when it matters most",
        "discovering they've been living a lie"
    ],
    "secrets": [
        "witnessed a crime but never reported it",
        "has a child they've never acknowledged",
        "was responsible for someone's death",
        "stole something valuable years ago",
        "is hiding their true identity from everyone",
        "has a terminal illness they haven't disclosed",
        "was abandoned as a child and never told anyone",
        "has been lying about their qualifications",
        "is secretly in love with their best friend's partner",
        "has been embezzling money to help their family",
        "was abused as a child but pretends it didn't happen",
        "has an addiction they've hidden successfully",
        "witnessed their parent commit a serious crime",
        "has been having an affair for years",
        "is actually wealthy but pretends to be poor",
        "has supernatural abilities they're hiding",
        "is adopted but was never told the truth",
        "was involved in covering up an accident",
        "has been blackmailed for years",
        "knows who killed someone but won't tell"
    ],
    "morality": [
        "believes the ends always justify the means",
        "follows a strict moral code regardless of consequences",
        "thinks morality is relative to circumstances",
        "believes in redemption for everyone",
        "thinks some people are beyond saving",
        "values loyalty above all other virtues",
        "believes in second chances but not third ones",
        "thinks survival trumps moral considerations",
        "believes in absolute truth and justice",
        "thinks tradition and law should guide decisions",
        "values individual freedom over collective good",
        "believes in protecting the innocent at any cost",
        "thinks progress requires breaking some rules",
        "values honesty even when it causes pain"
    ],
    "emotional_traits": [
        "wears their heart on their sleeve",
        "bottles up emotions until they explode",
        "uses humor to deflect serious conversations",
        "cries easily but hides it from others",
        "gets angry quickly but forgives just as fast",
        "struggles to express feelings verbally",
        "feels others' emotions too intensely",
        "compartmentalizes emotions to function",
        "seeks emotional validation constantly",
        "avoids emotional intimacy at all costs",
        "experiences emotions in extremes",
        "uses logic to suppress emotional responses",
        "gets overwhelmed by too much stimulation",
        "finds comfort in emotional routine"
    ],
    "background": {
        "socioeconomic": [
            "grew up in extreme poverty",
            "came from old money but lost it all",
            "middle class with working parents",
            "wealthy but emotionally neglected",
            "working class with strong family values",
            "inherited wealth but feels guilty about it",
            "self-made success from humble beginnings",
            "comfortable but constantly worried about money",
            "bounced between different economic classes",
            "poor but surrounded by love and support"
        ],
        "education": [
            "dropped out of high school to work",
            "highly educated but lacks practical skills",
            "self-taught in their area of expertise",
            "attended prestigious schools but felt like an outsider",
            "learned everything from the school of hard knocks",
            "formal education interrupted by family crisis",
            "brilliant but never had access to good schools",
            "overeducated and unable to relate to others",
            "specialized training in a narrow field",
            "well-rounded education but no clear direction"
        ]
    },
    "occupations": [
        "struggling artist or writer",
        "emergency room doctor or nurse",
        "detective or private investigator",
        "teacher at an underfunded school",
        "social worker dealing with tough cases",
        "journalist uncovering corruption",
        "small business owner fighting to survive",
        "therapist helping trauma victims",
        "activist fighting for social justice",
        "mechanic who fixes more than just cars",
        "librarian who knows everyone's secrets",
        "bartender who listens to life stories",
        "chef at a family restaurant",
        "veterinarian who cares too much",
        "construction worker building community",
        "security guard protecting others",
        "delivery driver connecting with customers",
        "translator bridging cultural gaps",
        "park ranger protecting nature",
        "funeral director comforting the grieving"
    ],
    "family_background": [
        "raised by a single parent who sacrificed everything",
        "grew up in foster care, never finding permanent home",
        "part of a large, chaotic but loving family",
        "only child of overprotective parents",
        "raised by grandparents after parents died",
        "split between divorced parents who hate each other",
        "grew up in a family business that's failing",
        "raised in a religious household with strict rules",
        "family has a dark secret everyone knows but won't discuss",
        "adopted into a family that never fully accepted them",
        "grew up with an abusive parent and protective siblings",
        "raised by parents who had them too young",
        "family torn apart by addiction or mental illness",
        "grew up wealthy but emotionally cold family",
        "raised in a family of overachievers where they didn't fit"
    ],
    "formative_experiences": [
        "survived a natural disaster that killed others",
        "was bullied severely throughout childhood",
        "witnessed domestic violence in their home",
        "had to grow up too fast due to family crisis",
        "was betrayed by their childhood best friend",
        "experienced a life-threatening illness",
        "lost a parent at a crucial age",
        "was abandoned or neglected as a child",
        "experienced racial or social discrimination",
        "had their trust broken by an authority figure",
        "survived an accident that changed their perspective",
        "was forced to move frequently during childhood",
        "experienced poverty that shaped their worldview",
        "had a mentor who believed in them when no one else did",
        "witnessed an injustice they couldn't prevent"
    ],
    "skills": {
        "primary": [
            "exceptional at reading people's motivations",
            "brilliant problem solver under pressure",
            "natural leader who inspires others",
            "gifted communicator who can persuade anyone",
            "incredibly observant and detail-oriented",
            "has an eidetic memory for faces and conversations",
            "natural healer who helps others feel better",
            "gifted with mechanical and technical things",
            "excellent at mediating conflicts",
            "incredible survival instincts",
            "naturally athletic and physically capable",
            "gifted artist who sees beauty everywhere",
            "excellent strategist and planner",
            "natural teacher who makes complex things simple",
            "gifted with animals and nature"
        ],
        "hidden": [
            "can sing beautifully but is too shy to perform",
            "is an excellent cook but never gets to show it",
            "has a photographic memory they've never revealed",
            "can pick locks and has other criminal skills",
            "is fluent in multiple languages",
            "has an uncanny ability to predict weather",
            "can do complex mathematical calculations mentally",
            "has perfect pitch and musical abilities",
            "is skilled in martial arts or self-defense",
            "can imitate voices and accents perfectly",
            "has an incredible green thumb with plants",
            "can read lips and body language expertly",
            "has eidetic memory for written text",
            "can detect lies with unusual accuracy"
        ]
    },
    "relationship_patterns": [
        "attracts people who need fixing",
        "pushes away anyone who gets too close",
        "becomes completely absorbed in their relationships",
        "maintains superficial connections with everyone",
        "gravitates toward people who remind them of their parent",
        "seeks out relationships where they can be the rescuer",
        "chooses partners who are emotionally unavailable",
        "forms intense friendships that burn out quickly",
        "surrounds themselves with people they can control",
        "seeks approval from people who will never give it",
        "attracts drama and chaotic relationships",
        "forms deep bonds but struggles with boundaries",
        "avoids commitment but craves connection",
        "becomes dependent on others for self-worth"
    ],
    "trust_patterns": [
        "trusts too easily and gets hurt repeatedly",
        "takes years to trust but then trusts completely",
        "trusts actions more than words",
        "has difficulty trusting anyone in authority",
        "trusts family but no one else",
        "only trusts people who've been through similar trauma",
        "trusts their instincts about people completely",
        "second-guesses everyone's motivations",
        "trusts too quickly when they're lonely",
        "tests people's loyalty before trusting them"
    ],
    "goals": {
        "short_term": [
            "save enough money to move to a better neighborhood",
            "reconnect with an estranged family member",
            "finish a creative project they've been working on",
            "get their life back on track after a major setback",
            "help a friend or family member through a crisis",
            "overcome a specific fear or phobia",
            "learn a new skill that could change their career",
            "find evidence to prove someone's innocence",
            "escape from a toxic relationship or situation",
            "make amends for a past mistake"
        ],
        "long_term": [
            "break the cycle of dysfunction in their family",
            "become the person their younger self needed",
            "create something that will outlast their lifetime",
            "find peace with their past trauma",
            "build a family that's healthier than the one they grew up in",
            "make a significant impact on their community",
            "prove that people like them can succeed",
            "find their true purpose in life",
            "leave the world better than they found it",
            "achieve a level of success that honors their sacrifices"
        ]
    },
    "internal_conflicts": [
        "wants to be independent but craves connection",
        "desires success but fears losing their authenticity",
        "wants to help others but struggles to help themselves",
        "craves stability but feels trapped by routine",
        "wants to be loved but fears being vulnerable",
        "desires revenge but knows it won't heal them",
        "wants to forgive but can't forget the pain",
        "craves adventure but fears leaving their comfort zone",
        "wants to trust others but has been betrayed before",
        "desires to be perfect but knows it's impossible"
    ],
    "positive_traits": [
        "fiercely loyal to those they love",
        "endlessly compassionate toward others' suffering",
        "incredibly resilient in the face of adversity",
        "naturally optimistic despite their struggles",
        "possesses unwavering integrity",
        "demonstrates remarkable courage when needed",
        "shows exceptional kindness to strangers",
        "maintains hope even in dark times",
        "exhibits profound wisdom beyond their years",
        "displays remarkable patience with difficult people",
        "shows genuine empathy for others' experiences",
        "demonstrates incredible determination",
        "possesses a natural sense of justice",
        "exhibits remarkable creativity and imagination",
        "shows exceptional generosity despite having little"
    ],
    "quirks": [
        "talks to plants and believes they listen",
        "collects something unusual and seemingly worthless",
        "has a ritual they perform before important events",
        "names inanimate objects and treats them like friends",
        "can't sleep without a specific comfort item",
        "has an unusual phobia of common things",
        "always carries a lucky charm or meaningful object",
        "has a specific way they arrange or organize everything",
        "talks to themselves when working through problems",
        "has an unusual talent for predicting random events",
        "always sits in the same spot wherever they go",
        "has a catchphrase or expression they use constantly",
        "counts things compulsively when nervous",
        "has to touch certain objects for good luck"
    ],
    "arcs": {
        "protagonist": [
            "learning to trust others despite past betrayals",
            "overcoming self-doubt to embrace their potential",
            "choosing between personal desires and greater good",
            "learning that true strength comes from vulnerability",
            "discovering that their greatest weakness is actually their strength",
            "realizing they've been their own worst enemy",
            "learning to forgive themselves for past mistakes",
            "discovering that they're more like their enemy than they thought",
            "learning that some battles can't be won alone",
            "realizing that their identity isn't defined by their trauma"
        ]
    },
    "call_to_adventure": [
        "discovers they have a terminal illness and limited time",
        "learns a devastating family secret that changes everything",
        "witnesses an injustice they can't ignore",
        "receives news that someone they love is in danger",
        "discovers they have an ability or heritage they never knew about",
        "is wrongfully accused of a serious crime",
        "finds evidence of a conspiracy that affects everyone",
        "inherits a responsibility they never wanted",
        "is chosen for a task they feel unqualified for",
        "discovers their entire life has been built on a lie"
    ],
    "mental_strength": [
        "unbreakable will forged by surviving trauma",
        "calm focus maintained even in chaos",
        "ability to compartmentalize emotions when necessary",
        "unwavering determination despite repeated failures",
        "capacity to find hope in the darkest situations",
        "resilience that bounces back from any setback",
        "emotional intelligence that reads any situation",
        "inner peace achieved through accepting their flaws",
        "strength drawn from protecting others",
        "wisdom gained through learning from mistakes"
    ],
    "corruption_sources": [
        "convinced that love is weakness after being betrayed",
        "believes the world is fundamentally unfair and cruel",
        "thinks they're protecting others by controlling them",
        "was hurt so badly they can't imagine genuine goodness",
        "believes that only power can prevent suffering",
        "convinced that emotions cloud judgment and cause pain",
        "thinks that most people are too weak to handle truth",
        "believes that order must be imposed on chaos",
        "was taught that showing mercy is showing weakness",
        "convinced that the ends always justify the means"
    ],
    "control_methods": [
        "uses others' guilt and shame against them",
        "isolates people from their support systems",
        "creates dependency by solving all their problems",
        "uses fear and intimidation to maintain order",
        "manipulates by appearing to be the victim",
        "controls information to shape others' reality",
        "uses others' love for someone against them",
        "creates chaos and then offers stability",
        "exploits others' insecurities and fears",
        "uses rewards and punishments to shape behavior"
    ],
    "supporting_roles": [
        "the loyal friend who always has the protagonist's back",
        "the wise mentor who provides guidance at crucial moments",
        "the comic relief who lightens tense situations",
        "the voice of reason when the protagonist acts rashly",
        "the connection to the protagonist's past",
        "the representation of what the protagonist could become",
        "the moral compass when the protagonist wavers",
        "the technical expert who provides needed skills",
        "the emotional support during difficult times",
        "the bridge between the protagonist and other groups"
    ],
    "loyalty_levels": [
        "would die for the protagonist without question",
        "loyal until their own family is threatened",
        "loyal as long as the cause remains just",
        "loyal but will call out the protagonist's mistakes",
        "conditionally loyal based on reciprocal treatment",
        "loyal to the idea more than the person",
        "loyal but has secret doubts about the protagonist",
        "appears loyal but has hidden agenda",
        "loyal but easily swayed by emotional appeals",
        "loyal only as long as it benefits them"
    ],
    "support_types": [
        "provides practical help and resources",
        "offers emotional comfort and understanding",
        "gives advice and wisdom from experience",
        "serves as a reality check and voice of reason",
        "provides comic relief and levity",
        "offers technical or specialized knowledge",
        "serves as a bridge to other characters or groups",
        "provides inspiration and motivation",
        "offers protection and physical support",
        "serves as a confidant for secrets and fears"
    ],
    "humor_styles": [
        "uses self-deprecating humor to deflect attention",
        "makes witty observations about absurd situations",
        "tells stories that are funnier than they realize",
        "uses physical comedy and timing",
        "makes jokes to cope with trauma and stress",
        "delivers dry, deadpan observations",
        "uses wordplay and clever language",
        "finds humor in others' quirks and habits",
        "makes unexpected connections between unrelated things",
        "uses gentle teasing to show affection"
    ],
    "comedy_sources": [
        "completely misunderstands social norms",
        "takes everything too literally",
        "has unusual phobias or obsessions",
        "constantly misreads romantic situations",
        "is incredibly unlucky in harmless ways",
        "has strong opinions about trivial things",
        "consistently overreacts to minor problems",
        "has unusual skills that come up at odd times",
        "misinterprets common expressions",
        "has a running feud with an inanimate object"
    ],
    "serious_depth": [
        "reveals hidden wisdom during a crisis",
        "shows unexpected courage when others are in danger",
        "demonstrates deep loyalty despite their jokes",
        "has a tragic backstory that explains their humor",
        "becomes fiercely protective when someone is threatened",
        "shows profound understanding of others' pain",
        "reveals they use humor to cope with depression",
        "demonstrates surprising competence in emergencies",
        "shows deep insecurity beneath their confident exterior",
        "reveals they make jokes because they're afraid of being ignored"
    ],
    "wisdom_sources": [
        "learned from making terrible mistakes in the past",
        "gained insight through surviving great loss",
        "developed understanding through years of observation",
        "earned wisdom by helping others through their problems",
        "achieved clarity through meditation and reflection",
        "learned from a mentor who taught them well",
        "gained perspective through traveling and seeing different ways of life",
        "developed wisdom through studying ancient texts or philosophy",
        "learned through trial and error over many years",
        "gained insight through surviving their own dark period"
    ],
    "teaching_methods": [
        "tells stories that contain deeper lessons",
        "asks questions that lead students to discover answers",
        "demonstrates through actions rather than words",
        "provides challenges that build character",
        "offers support while allowing students to struggle",
        "shares personal failures as learning opportunities",
        "creates situations where students must solve problems",
        "uses metaphors and analogies to explain concepts",
        "provides just enough help to keep students from giving up",
        "teaches by example, living the principles they teach"
    ],
    "mentor_failures": [
        "failed to save someone they cared about",
        "trusted the wrong person and paid a heavy price",
        "let pride prevent them from asking for help",
        "made a decision that harmed innocent people",
        "was too controlling and drove away someone they loved",
        "ignored warning signs that led to disaster",
        "chose duty over family and lost both",
        "was too trusting and was betrayed by a student",
        "let fear prevent them from taking necessary action",
        "was too harsh and broke someone's spirit"
    ],
    "romantic_qualities": [
        "makes others feel truly seen and understood",
        "has a passionate intensity that's magnetic",
        "demonstrates unwavering loyalty and devotion",
        "possesses a mysterious depth that intrigues others",
        "shows vulnerability that makes others want to protect them",
        "has a playful spirit that brings joy to others",
        "demonstrates strength that makes others feel safe",
        "possesses a gentle kindness that heals emotional wounds",
        "has an adventurous spirit that inspires others",
        "shows authenticity that encourages others to be themselves"
    ],
    "romantic_styles": [
        "slow to trust but loves deeply once committed",
        "passionate and intense, loves with their whole heart",
        "playful and fun, keeps romance light and joyful",
        "devoted and loyal, puts their partner's needs first",
        "independent but caring, maintains their own identity",
        "romantic and idealistic, believes in fairy tale love",
        "practical and steady, shows love through actions",
        "protective and possessive, sometimes to a fault",
        "spontaneous and unpredictable, keeps things exciting",
        "supportive and encouraging, helps their partner grow"
    ],
    "romantic_conflicts": [
        "fears that love makes them vulnerable to hurt",
        "struggles with jealousy and possessiveness",
        "has commitment issues due to past trauma",
        "loves someone they believe they can't have",
        "is torn between duty and desire",
        "fears their dark past will drive their love away",
        "has to choose between love and their life's mission",
        "loves someone from an opposing faction or family",
        "struggles with insecurity about their worthiness",
        "fears that their love will endanger the other person"
    ]
}
